x-scraper-base: &scraper-base
  build:
    context: .
    dockerfile: dockerfile
  image: deezer_scraper:latest
  dns:
    - 8.8.8.8
    - 1.1.1.1
  depends_on:
    postgres:
      condition: service_healthy
  stop_grace_period: 60s

services:
  postgres:
    image: postgres:16-alpine
    container_name: deezer_db
    environment:
      POSTGRES_DB: deezer
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d deezer"]
      interval: 5s
      retries: 5

  scraper_artist:
    <<: *scraper-base
    container_name: deezer_scraper_artist
    command: ["python", "main.py", "artist"]
    environment:
      ARTIST_REQUESTS_PER_SECOND: "6.5"
    restart: unless-stopped

  scraper_user:
    <<: *scraper-base
    container_name: deezer_scraper_user
    command: ["python", "main.py", "user"]
    environment:
      USER_REQUESTS_PER_SECOND: "3"
    restart: unless-stopped

  scraper_genre_detail:
    <<: *scraper-base
    container_name: deezer_scraper_genre
    command: ["python", "main.py", "genre_detail"]
    environment:
      GENRE_REQUESTS_PER_SECOND: "10"
    restart: "no"
    profiles: [jobs]

  scraper_album_detail:
    <<: *scraper-base
    container_name: deezer_scraper_album_detail
    command: ["python", "main.py", "album_detail"]
    environment:
      ALBUM_DETAIL_REQUESTS_PER_SECOND: "10"
    restart: "no"
    profiles: [jobs]

  scraper_track_detail:
    <<: *scraper-base
    container_name: deezer_scraper_track_detail
    command: ["python", "main.py", "track_detail"]
    environment:
      TRACK_DETAIL_REQUESTS_PER_SECOND: "10"
    restart: "no"
    profiles: [jobs]

  superset:
    build:
      context: ./superset
      dockerfile: dockerfile
    container_name: deezer_superset
    environment:
      SUPERSET_SECRET_KEY: "supersecretkey123"
    ports:
      - "8700:8088"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - superset_home:/app/superset_home

volumes:
  postgres_data:
  superset_home: