FROM python:3.11-slim

WORKDIR /app

RUN pip install requests psycopg2-binary

COPY config.py .
COPY db.py .
COPY artist_scraper.py .
COPY album_scraper.py .
COPY track_scraper.py .
COPY user_scraper.py .
COPY coordinator_artist_scrape.py .
COPY coordinator_user_scrape.py .
COPY main.py .

CMD ["python", "main.py"]
